# -*- coding: utf-8 -*-
"""KRITI2026_CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGDD-eoxS5CCdeS5Z7jb-BBSZWVNDp2Z
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

data = pd.read_parquet('/content/drive/MyDrive/Colab Notebooks/nse_prices_complete 1(1).parquet')

df = data.copy()

# ============================================================
# Training
# ============================================================

!pip -q install xgboost

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from xgboost import XGBRegressor

# ----------------------------
# CONFIG (DF-ONLY)
# ----------------------------
START_DATE = "2010-01-01"
END_DATE   = "2020-01-01"

# internal training split (to reduce overfitting while still "df-only"):
# - train: 2010-2018
# - validate: 2019 (used only for invest_frac selection, optional)
# - report/backtest: 2010-2020 (final equity curve)
TRAIN_START = "2010-01-01"
TRAIN_END   = "2018-12-31"
VAL_START   = "2019-01-01"
VAL_END     = "2019-12-31"

FWD_HORIZON_DAYS = 21

ATR_N = 21
SUPERTREND_ATR_N = 14
SUPERTREND_MULT  = 3.0
GAUSS_MULT = 4.0

REGIME_WINDOW = 252
SMOOTH_PASSES = 6
EXTREMA_NEED  = 4

# Kriti mandatory style
INITIAL_CAPITAL = 5_000_000.0  # ₹50,00,000
MAX_HOLDINGS = 100
MIN_HOLDINGS = 1  # "except cash calls" -> enforced unless portfolio is empty and no signals
MIN_HOLD_DAYS = 1
MAX_HOLD_DAYS = 100

# Costs: 0.268% per side at execution price
COST = 0.00268

# Stops
STOP_ATR_MULT = 1.5
# Small/Mid additions
TRAIL_ATR_MULT = 1.0
BREAKEVEN_ATR_MULT = 1.0

# Allocation calibration (done on TRAIN/VAL only)
INVEST_FRAC_GRID = [0.20, 0.35, 0.50, 0.65, 0.80, 0.95]

ANNUAL_TRADING_DAYS = 252

# ----------------------------
# REQUIRED DF CHECK
# ----------------------------
assert "df" in globals(), "You must have a DataFrame named `df` loaded before running."

required_cols = [
    "tradedate","open","high","low","close","traded_volume","fid",
    "cap_classification","in_NSE500"
]
missing = [c for c in required_cols if c not in df.columns]
assert not missing, f"Missing required columns in df: {missing}"

# ----------------------------
# UTILITIES (CAUSAL ONLY)
# ----------------------------
def typical_price(o, h, l, c):
    return (o + h + l + c) / 4.0

def ema_causal(x, span):
    return pd.Series(x).ewm(span=span, adjust=False).mean().to_numpy()

def atr(high, low, close, n=21):
    high = np.asarray(high, float)
    low  = np.asarray(low, float)
    close = np.asarray(close, float)
    prev_close = np.roll(close, 1)
    prev_close[0] = close[0]
    tr = np.maximum(high - low, np.maximum(np.abs(high - prev_close), np.abs(low - prev_close)))
    return pd.Series(tr).ewm(span=n, adjust=False).mean().to_numpy()

def supertrend(high, low, close, atr_n=10, mult=3.0):
    high = np.asarray(high, float)
    low  = np.asarray(low, float)
    close = np.asarray(close, float)

    a = atr(high, low, close, n=atr_n)
    hl2 = (high + low) / 2.0
    upperband = hl2 + mult * a
    lowerband = hl2 - mult * a

    st = np.zeros_like(close, dtype=float)
    direction = np.ones_like(close, dtype=int)

    st[0] = upperband[0]
    direction[0] = 1

    for i in range(1, len(close)):
        fub = upperband[i] if (upperband[i] < upperband[i-1] or close[i-1] > upperband[i-1]) else upperband[i-1]
        flb = lowerband[i] if (lowerband[i] > lowerband[i-1] or close[i-1] < lowerband[i-1]) else lowerband[i-1]

        if direction[i-1] == 1:
            direction[i] = -1 if close[i] <= fub else 1
        else:
            direction[i] = 1 if close[i] >= flb else -1

        st[i] = flb if direction[i] == 1 else fub
        upperband[i], lowerband[i] = fub, flb

    return direction.astype(float), st

def monthly_cpr_from_daily(daily_df):
    x = daily_df.copy()
    x["tradedate"] = pd.to_datetime(x["tradedate"])
    x["month"] = x["tradedate"].dt.to_period("M")

    m = x.groupby("month").agg(
        m_high=("high", "max"),
        m_low=("low", "min"),
        m_close=("close", "last"),
    ).reset_index()

    m["pivot"] = (m["m_high"] + m["m_low"] + m["m_close"]) / 3.0
    m["bc"] = (m["m_high"] + m["m_low"]) / 2.0
    m["tc"] = 2.0 * m["pivot"] - m["bc"]

    m[["pivot_prev","bc_prev","tc_prev"]] = m[["pivot","bc","tc"]].shift(1)
    x = x.merge(m[["month","pivot_prev","bc_prev","tc_prev"]], on="month", how="left")
    return x[["pivot_prev","bc_prev","tc_prev"]].to_numpy()

def gaussian_filter_causal(series, passes=6, span=20):
    y = np.asarray(series, dtype=float)
    for _ in range(passes):
        y = ema_causal(y, span=span)
    return y

def find_last_extrema(y):
    y = np.asarray(y, float)
    dy = np.diff(y)
    s = np.sign(dy)
    s[s == 0] = 1
    ds = np.diff(s)
    maxima = np.where(ds < 0)[0] + 1
    minima = np.where(ds > 0)[0] + 1
    extrema = np.sort(np.concatenate([maxima, minima]))
    return extrema, maxima, minima

def regime_from_last4_extrema(smoothed_window):
    y = np.asarray(smoothed_window, float)
    extrema, maxima, minima = find_last_extrema(y)
    if len(extrema) < EXTREMA_NEED:
        return "sideways"
    last_ext = extrema[-EXTREMA_NEED:]
    max_set, min_set = set(maxima), set(minima)
    last_max = [i for i in last_ext if i in max_set]
    last_min = [i for i in last_ext if i in min_set]
    if len(last_max) < 2 or len(last_min) < 2:
        return "sideways"
    max1, max2 = last_max[-2], last_max[-1]
    min1, min2 = last_min[-2], last_min[-1]
    if y[max2] > y[max1] and y[min2] > y[min1]:
        return "up"
    if y[max2] < y[max1] and y[min2] < y[min1]:
        return "down"
    return "sideways"

def compute_regime_per_stock(close_series):
    close = np.asarray(close_series, float)
    sm = gaussian_filter_causal(close, passes=SMOOTH_PASSES, span=20)
    regimes = np.empty(len(close), dtype=object)
    for i in range(len(close)):
        start = max(0, i - REGIME_WINDOW + 1)
        window = sm[start:i+1]
        regimes[i] = regime_from_last4_extrema(window) if len(window) >= 60 else "sideways"
    return regimes, sm

def max_drawdown(equity_curve):
    ec = np.asarray(equity_curve, float)
    peak = np.maximum.accumulate(ec)
    dd = (ec / peak) - 1.0
    return float(dd.min()), dd

def cagr(equity_curve, dates):
    ec = np.asarray(equity_curve, float)
    if len(ec) < 2:
        return 0.0
    start = pd.to_datetime(dates[0])
    end   = pd.to_datetime(dates[-1])
    years = max((end - start).days / 365.25, 1e-9)
    return (ec[-1] / ec[0]) ** (1.0 / years) - 1.0

# ----------------------------
# BENCHMARK (DF-ONLY PROXY)
# If you don't have an index series, we build a daily equal-weight NSE500 proxy
# using close-to-close returns across rows with in_NSE500==True.
# This stays within "provided dataset only".
# ----------------------------
def build_nse500_proxy_returns(data_all):
    x = data_all[data_all["in_NSE500"].astype(bool)].copy()
    x.sort_values(["fid","tradedate"], inplace=True)
    x["ret"] = x.groupby("fid")["close"].pct_change()
    # equal-weight across available NSE500 names each day
    bench = x.groupby("tradedate")["ret"].mean().fillna(0.0)
    return bench

def information_ratio(strategy_rets, bench_rets):
    # IR = mean(active)/std(active) * sqrt(252)
    a = (strategy_rets - bench_rets).dropna()
    if len(a) < 2:
        return 0.0
    te = a.std(ddof=1)
    return 0.0 if te <= 1e-12 else np.sqrt(ANNUAL_TRADING_DAYS) * a.mean() / te

def up_down_capture(strategy_rets, bench_rets):
    s = strategy_rets.align(bench_rets, join="inner")[0]
    b = strategy_rets.align(bench_rets, join="inner")[1]
    up = b > 0
    down = b < 0
    up_cap = (s[up].mean() / b[up].mean()) if up.any() and abs(b[up].mean()) > 1e-12 else 0.0
    down_cap = (s[down].mean() / b[down].mean()) if down.any() and abs(b[down].mean()) > 1e-12 else 0.0
    return float(up_cap), float(down_cap)

def rolling_outperformance(strategy_rets, bench_rets, years):
    win = years * ANNUAL_TRADING_DAYS
    s, b = strategy_rets.align(bench_rets, join="inner")
    active = (s - b).fillna(0.0)
    if len(active) < win:
        return None
    roll = active.rolling(win).sum()
    return float(roll.mean()), float(roll.min())

# ----------------------------
# DATA PREP (2010–2020 only)
# ----------------------------
data = df.copy()
data["tradedate"] = pd.to_datetime(data["tradedate"])
data = data[(data["tradedate"] >= pd.to_datetime(START_DATE)) & (data["tradedate"] <= pd.to_datetime(END_DATE))].copy()

# normalize cap labels
data["cap_classification"] = (
    data["cap_classification"].astype(str).str.lower().str.replace(r"[\s\-]", "", regex=True)
)

# we only route on these buckets; anything else -> treated as small/mid engine by default
def bucket(x):
    if x == "largecap":
        return "largecap"
    if x in ("smallcap","midcap"):
        return "smallmid"
    return "smallmid"

data["cap_bucket"] = data["cap_classification"].map(bucket)

data.sort_values(["fid","tradedate"], inplace=True)
data.reset_index(drop=True, inplace=True)

print("Rows:", len(data), "Unique fids:", data["fid"].nunique())
print("Largecap fids:", data[data.cap_bucket=="largecap"]["fid"].nunique(),
      "| Small/Mid fids:", data[data.cap_bucket=="smallmid"]["fid"].nunique())

bench_rets = build_nse500_proxy_returns(data)

# ----------------------------
# FEATURE ENGINEERING (PER STOCK, CAUSAL)
# We build ALL columns, but each bucket uses its own feature set/model.
# ----------------------------
rows = []
for fid, g in data.groupby("fid", sort=False):
    g = g.copy()
    g.sort_values("tradedate", inplace=True)

    g["atr21"] = atr(g["high"].to_numpy(), g["low"].to_numpy(), g["close"].to_numpy(), n=ATR_N)
    st_dir, st_val = supertrend(g["high"].to_numpy(), g["low"].to_numpy(), g["close"].to_numpy(),
                               atr_n=SUPERTREND_ATR_N, mult=SUPERTREND_MULT)
    g["st_dir"] = st_dir
    g["st_val"] = st_val

    regimes, sm_close = compute_regime_per_stock(g["close"].to_numpy())
    g["regime"] = regimes
    g["gauss_basis"] = sm_close
    g["gauss_upper"] = g["gauss_basis"] + GAUSS_MULT * g["atr21"]
    g["gauss_lower"] = g["gauss_basis"] - GAUSS_MULT * g["atr21"]
    denom = (g["gauss_upper"] - g["gauss_lower"]).replace(0, np.nan)
    g["gauss_pos"] = (g["close"] - g["gauss_lower"]) / denom

    g["log_volume"] = np.log1p(g["traded_volume"].astype(float))

    # CPR (only used by largecap model)
    cpr = monthly_cpr_from_daily(g[["tradedate","open","high","low","close"]])
    g["cpr_pivot_prev"] = cpr[:,0]
    g["cpr_bc_prev"]    = cpr[:,1]
    g["cpr_tc_prev"]    = cpr[:,2]
    g["cpr_width_prev"] = (g["cpr_tc_prev"] - g["cpr_bc_prev"]).abs().replace(0, np.nan)
    g["dist_to_pivot_prev"] = (g["close"] - g["cpr_pivot_prev"]) / g["cpr_width_prev"]
    g["dist_to_bc_prev"]    = (g["close"] - g["cpr_bc_prev"]) / g["cpr_width_prev"]
    g["dist_to_tc_prev"]    = (g["close"] - g["cpr_tc_prev"]) / g["cpr_width_prev"]

    # MAs (only used by small/mid model)
    g["sma7"] = g["close"].rolling(window=7, min_periods=1).mean()
    g["ema50"] = g["close"].ewm(span=50, adjust=False, min_periods=1).mean()
    atr_safe = g["atr21"].replace(0, np.nan)
    g["dist_to_sma7"] = (g["close"] - g["sma7"]) / atr_safe
    g["dist_to_ema50"] = (g["close"] - g["ema50"]) / atr_safe
    g["dist_sma7_ema50"] = (g["sma7"] - g["ema50"]) / atr_safe

    # supervised target (future; only for training target)
    g["fwd_ret"] = g["close"].shift(-FWD_HORIZON_DAYS) / g["close"] - 1.0

    rows.append(g)

panel = pd.concat(rows, axis=0).sort_values(["tradedate","fid"]).reset_index(drop=True)
panel = panel.dropna(subset=["open","high","low","close","atr21","gauss_pos","log_volume","fwd_ret","st_dir"]).copy()

# ----------------------------
# TRAIN TWO MODELS (DF-ONLY, TRAIN_START..TRAIN_END)
# ----------------------------
LC_FEATURES = ["log_volume","st_dir","atr21","dist_to_pivot_prev","dist_to_bc_prev","dist_to_tc_prev","gauss_pos"]
SM_FEATURES = ["log_volume","st_dir","atr21","dist_to_sma7","dist_to_ema50","dist_sma7_ema50","gauss_pos"]

def calibrate_thresholds(train_scored):
    regimes = ["up","down","sideways"]
    thr = {}
    for r in regimes:
        df_r = train_scored[train_scored["regime"].eq(r)].copy()
        if len(df_r) < 2000:
            df_r = train_scored.copy()
        s = df_r["XGy"].to_numpy()
        y = df_r["fwd_ret"].to_numpy()
        pos = (y > 0).astype(int)
        neg = (y < 0).astype(int)

        q = np.linspace(0.50, 0.98, 25)
        buy_cand = np.quantile(s, q)
        sell_cand = np.quantile(s, 1.0 - q)

        best_buy, best_prec = None, -1
        for t in buy_cand:
            m = s >= t
            if m.sum() < 200:
                continue
            prec = pos[m].mean()
            if prec > best_prec:
                best_prec, best_buy = prec, t

        best_sell, best_nprec = None, -1
        for t in sell_cand:
            m = s <= t
            if m.sum() < 200:
                continue
            nprec = neg[m].mean()
            if nprec > best_nprec:
                best_nprec, best_sell = nprec, t

        if best_buy is None:  best_buy = np.quantile(s, 0.85)
        if best_sell is None: best_sell = np.quantile(s, 0.30)
        if best_sell > best_buy:
            best_sell = min(best_buy, np.quantile(s, 0.35))

        thr[r] = {"tBuy": float(best_buy), "tSell": float(best_sell)}
    return thr

train_mask = (panel["tradedate"] >= pd.to_datetime(TRAIN_START)) & (panel["tradedate"] <= pd.to_datetime(TRAIN_END))

panel_lc = panel[panel["cap_bucket"]=="largecap"].copy()
panel_sm = panel[panel["cap_bucket"]=="smallmid"].copy()

# Largecap model
lc_train = panel_lc[train_mask.reindex(panel_lc.index, fill_value=False)].copy()
lc_model = XGBRegressor(
    n_estimators=600, max_depth=5, learning_rate=0.03,
    subsample=0.8, colsample_bytree=0.8,
    min_child_weight=5, reg_lambda=1.0,
    random_state=42, n_jobs=-1
)
lc_model.fit(lc_train[LC_FEATURES].to_numpy(), lc_train["fwd_ret"].to_numpy())
panel_lc["XGy"] = lc_model.predict(panel_lc[LC_FEATURES].to_numpy())
lc_thr = calibrate_thresholds(panel_lc[train_mask.reindex(panel_lc.index, fill_value=False)].copy())

# Small/Mid model
sm_train = panel_sm[train_mask.reindex(panel_sm.index, fill_value=False)].copy()
sm_model = XGBRegressor(
    n_estimators=600, max_depth=5, learning_rate=0.03,
    subsample=0.8, colsample_bytree=0.8,
    min_child_weight=5, reg_lambda=1.0,
    random_state=42, n_jobs=-1
)
sm_model.fit(sm_train[SM_FEATURES].to_numpy(), sm_train["fwd_ret"].to_numpy())
panel_sm["XGy"] = sm_model.predict(panel_sm[SM_FEATURES].to_numpy())
sm_thr = calibrate_thresholds(panel_sm[train_mask.reindex(panel_sm.index, fill_value=False)].copy())

unified = pd.concat([panel_lc, panel_sm], axis=0).sort_values(["tradedate","fid"]).reset_index(drop=True)

print("Training complete.")
print("LC thresholds:", lc_thr)
print("SM thresholds:", sm_thr)

# ----------------------------
# Testing
# ----------------------------
def backtest_unified(panel_df, start_date, end_date, invest_frac_lc, invest_frac_sm, lc_thr, sm_thr):
    dfp = panel_df[(panel_df["tradedate"] >= pd.to_datetime(start_date)) & (panel_df["tradedate"] <= pd.to_datetime(end_date))].copy()
    dfp.sort_values(["tradedate","fid"], inplace=True)

    dates = dfp["tradedate"].drop_duplicates().sort_values().to_list()
    by_date = {d: g for d, g in dfp.groupby("tradedate", sort=False)}

    cash = INITIAL_CAPITAL
    positions = {}  # fid -> position dict
    equity_curve, hold_count = [], []
    daily_ret = []
    trade_log = []
    turnover_value = 0.0

    prev_equity = INITIAL_CAPITAL

    for i in range(len(dates) - 1):
        d0, d1 = dates[i], dates[i+1]
        g0, g1 = by_date.get(d0), by_date.get(d1)
        if g0 is None or g1 is None:
            continue

        row0 = {int(r.fid): r for r in g0.itertuples(index=False)}
        row1 = {int(r.fid): r for r in g1.itertuples(index=False)}

        # ---- Mark-to-market at close of d0
        eq = cash
        for fid, pos in positions.items():
            px = float(row0[fid].close) if fid in row0 else pos["last_close"]
            eq += pos["shares"] * px
        equity_curve.append(eq)
        hold_count.append(len(positions))
        daily_ret.append((eq / prev_equity) - 1.0)
        prev_equity = eq

        # ---- Update last_close for robustness
        for fid, pos in positions.items():
            if fid in row0:
                pos["last_close"] = float(row0[fid].close)

        # ---- Forced exits on d1 (stop / max hold) with bucket-specific stop management
        forced_sells = []
        for fid, pos in list(positions.items()):
            pos["hold_days"] += 1

            if fid not in row1:
                continue

            r1 = row1[fid]
            low1 = float(r1.low)
            close1 = float(r1.close)
            atr1 = float(r1.atr21)

            if pos["bucket"] == "smallmid":
                # breakeven ratchet trigger using entry ATR
                pos["highest_close"] = max(pos["highest_close"], close1)
                if (pos["highest_close"] - pos["entry_px"]) >= (BREAKEVEN_ATR_MULT * pos["entry_atr"]):
                    pos["breakeven_active"] = True

                if pos["breakeven_active"]:
                    trail_stop = pos["highest_close"] - (TRAIL_ATR_MULT * atr1)
                    pos["stop_px"] = max(pos["stop_px"], pos["entry_px"], trail_stop)
                else:
                    pos["stop_px"] = max(pos["stop_px"], pos["entry_px"] - STOP_ATR_MULT * pos["entry_atr"])

            # hard exit
            if pos["hold_days"] >= MAX_HOLD_DAYS or low1 <= pos["stop_px"]:
                forced_sells.append((fid, "forced"))

        # execute forced sells at d1 typical price, net of costs
        for fid, why in forced_sells:
            if fid not in positions or fid not in row1:
                continue
            r1 = row1[fid]
            exec_px = typical_price(float(r1.open), float(r1.high), float(r1.low), float(r1.close))
            net_px = exec_px * (1.0 - COST)
            val = positions[fid]["shares"] * net_px
            cash += val
            turnover_value += (positions[fid]["shares"] * exec_px)  # turnover on gross exec price
            trade_log.append((d1, fid, "SELL", positions[fid]["bucket"], positions[fid]["shares"], exec_px, "forced"))
            del positions[fid]

        # ---- Signal sells on d0, executed on d1
        signal_sells = []
        for fid, pos in list(positions.items()):
            if fid not in row0 or fid not in row1:
                continue
            r0 = row0[fid]
            reg = str(r0.regime)
            thr = lc_thr if pos["bucket"]=="largecap" else sm_thr
            tSell = thr.get(reg, thr["sideways"])["tSell"]

            if float(r0.XGy) <= tSell and pos["hold_days"] >= MIN_HOLD_DAYS:
                signal_sells.append(fid)

        # "minimum 1 holding except cash calls": avoid selling last position if there are no buys queued
        # (unless it was forced already, handled above)
        # We approximate "buys queued" by checking if any candidate exists on d0.
        # We'll compute candidates first, then decide if we allow last sell.
        # So defer execution until after candidate build.

        # ---- Build buy candidates from d0, executed on d1 (bucket-specific thresholds)
        candidates = []
        for r in g0.itertuples(index=False):
            fid = int(r.fid)
            if fid in positions:
                continue
            if fid not in row1:
                continue
            if pd.isna(r.XGy) or pd.isna(r.atr21):
                continue

            bucket = str(r.cap_bucket)
            thr = lc_thr if bucket=="largecap" else sm_thr
            reg = str(r.regime)
            tBuy = thr.get(reg, thr["sideways"])["tBuy"]
            if float(r.XGy) >= tBuy:
                candidates.append((fid, float(r.XGy), float(r.atr21), bucket, reg))

        # now enforce "min holdings" logic for signal sells
        if len(positions) == 1 and len(signal_sells) == 1 and len(candidates) == 0:
            # keep the last position (cash call exception not applicable because we already hold one)
            signal_sells = []

        for fid in signal_sells:
            if fid not in positions or fid not in row1:
                continue
            r1 = row1[fid]
            exec_px = typical_price(float(r1.open), float(r1.high), float(r1.low), float(r1.close))
            net_px = exec_px * (1.0 - COST)
            val = positions[fid]["shares"] * net_px
            cash += val
            turnover_value += (positions[fid]["shares"] * exec_px)
            trade_log.append((d1, fid, "SELL", positions[fid]["bucket"], positions[fid]["shares"], exec_px, "signal"))
            del positions[fid]

        # ---- Buys: budget split by bucket, max holdings cap
        if candidates and len(positions) < MAX_HOLDINGS and cash > 0:
            # cap number of new names so we never exceed MAX_HOLDINGS
            room = MAX_HOLDINGS - len(positions)
            candidates = sorted(candidates, key=lambda x: x[1], reverse=True)[:room]

            # split candidates by bucket
            cand_lc = [c for c in candidates if c[3] == "largecap"]
            cand_sm = [c for c in candidates if c[3] == "smallmid"]

            # allocate separate budgets
            budget_lc = cash * invest_frac_lc
            budget_sm = cash * invest_frac_sm

            def execute_buys(cands, budget, bucket_name):
                nonlocal cash, turnover_value, positions, trade_log
                if not cands or budget <= 0:
                    return
                scores = np.array([max(c[1], 0.0) for c in cands], float)
                ssum = scores.sum()
                if ssum <= 1e-12:
                    return
                for (fid, sc, atr_val, bucket, reg) in cands:
                    r1 = row1[fid]
                    exec_px = typical_price(float(r1.open), float(r1.high), float(r1.low), float(r1.close))
                    gross_px = exec_px * (1.0 + COST)

                    w = max(sc, 0.0) / ssum
                    alloc = budget * w

                    shares = int(alloc // gross_px)
                    if shares <= 0:
                        continue

                    cost_val = shares * gross_px
                    if cost_val > cash:
                        continue

                    cash -= cost_val
                    turnover_value += (shares * exec_px)
                    positions[fid] = {
                        "bucket": bucket,
                        "shares": shares,
                        "entry_px": exec_px,
                        "entry_atr": float(atr_val),
                        "stop_px": exec_px - STOP_ATR_MULT * float(atr_val),
                        "hold_days": 0,
                        "last_close": float(r1.close),
                        # small/mid extras (safe for largecap too)
                        "highest_close": float(r1.close),
                        "breakeven_active": False,
                    }
                    trade_log.append((d1, fid, "BUY", bucket, shares, exec_px, "signal"))

            execute_buys(cand_lc, budget_lc, "largecap")
            execute_buys(cand_sm, budget_sm, "smallmid")

        # enforce MAX_HOLDINGS (hard)
        if len(positions) > MAX_HOLDINGS:
            # should never happen due to room cap; keep as safety
            # if it does, drop lowest XGy names at next day (not ideal)
            pass

    res = {
        "dates": pd.to_datetime(dates[:len(equity_curve)]),
        "equity": np.array(equity_curve, float),
        "daily_ret": pd.Series(daily_ret, index=pd.to_datetime(dates[:len(equity_curve)])),
        "hold_count": pd.Series(hold_count, index=pd.to_datetime(dates[:len(equity_curve)])),
        "turnover_value": float(turnover_value),
        "trade_log": pd.DataFrame(trade_log, columns=["date","fid","side","bucket","shares","exec_px","reason"])
    }
    return res

# ----------------------------
# INVEST_FRAC CALIBRATION (DF-ONLY, TRAIN/VAL)
# We choose fractions that maximize Sharpe on VAL period (2019) to reduce in-sample bias.
# If VAL has too few days, fallback to TRAIN.
# ----------------------------
def sharpe(sr_rets):
    r = sr_rets.dropna().to_numpy()
    if len(r) < 2:
        return 0.0
    vol = r.std(ddof=1)
    return 0.0 if vol <= 1e-12 else np.sqrt(ANNUAL_TRADING_DAYS) * r.mean() / vol

def pick_best_invest_fracs(panel_df):
    best = {"lc": None, "sm": None, "sharpe": -1e9}
    # decide evaluation window
    eval_start, eval_end = (VAL_START, VAL_END)
    if pd.to_datetime(eval_end) <= pd.to_datetime(eval_start):
        eval_start, eval_end = (TRAIN_START, TRAIN_END)

    for flc in INVEST_FRAC_GRID:
        for fsm in INVEST_FRAC_GRID:
            res = backtest_unified(panel_df, eval_start, eval_end, flc, fsm, lc_thr, sm_thr)
            s = sharpe(res["daily_ret"])
            if s > best["sharpe"]:
                best = {"lc": flc, "sm": fsm, "sharpe": s}
    return best

best = pick_best_invest_fracs(unified)
print("Best invest fracs (VAL-optimized):", best, "\n")

# ----------------------------
# FINAL DF-ONLY BACKTEST (2010–2020)
# ----------------------------
final = backtest_unified(unified, START_DATE, END_DATE, best["lc"], best["sm"], lc_thr, sm_thr)

ec = pd.Series(final["equity"], index=final["dates"])
rets = final["daily_ret"].copy()

# Required metrics
cagr_val = cagr(ec.values, ec.index)
ann_vol = rets.std(ddof=1) * np.sqrt(ANNUAL_TRADING_DAYS)
mdd, dd = max_drawdown(ec.values)

bench = bench_rets.reindex(ec.index).fillna(0.0)
ir = information_ratio(rets, bench)
up_cap, down_cap = up_down_capture(rets, bench)

# rolling outperformance
roll_1y = rolling_outperformance(rets, bench, 1)
roll_3y = rolling_outperformance(rets, bench, 3)
roll_5y = rolling_outperformance(rets, bench, 5)

# turnover ratio = total traded value / avg equity
avg_eq = float(ec.mean()) if len(ec) else INITIAL_CAPITAL
turnover_ratio = final["turnover_value"] / max(avg_eq, 1e-9)

print("===== KRITI 2026 — DF-ONLY (2010–2020) REPORT =====")
print(f"Initial Capital: ₹{INITIAL_CAPITAL:,.0f}")
print(f"Sharpe Ratio: {ir:.3f}")
print(f"Final Equity:    ₹{ec.iloc[-1]:,.2f}")
print(f"CAGR:            {cagr_val*100:.2f}%")
print(f"Ann. Vol:        {ann_vol*100:.2f}%")
print(f"Max Drawdown:    {mdd*100:.2f}%")
print(f"Information Ratio (vs NSE500 proxy): {ir:.3f}")
print(f"Up Capture:      {up_cap:.3f}")
print(f"Down Capture:    {down_cap:.3f}")
print(f"Turnover:        {turnover_ratio:.3f}x")
print(f"Avg Holdings:    {final['hold_count'].mean():.2f} | Max Holdings: {final['hold_count'].max():.0f}")

def fmt_roll(x):
    if x is None:
        return "N/A"
    return f"avg={x[0]*100:.2f}%, worst={x[1]*100:.2f}%"

print(f"Rolling active (1Y): {fmt_roll(roll_1y)}")
print(f"Rolling active (3Y): {fmt_roll(roll_3y)}")
print(f"Rolling active (5Y): {fmt_roll(roll_5y)}")

# ----------------------------
# PLOTS (NAV, DD, Holdings)
# ----------------------------
plt.figure(figsize=(12,4))
plt.plot(ec.index, ec.values)
plt.title("Equity Curve (DF-only, T+1 typical, costs applied)")
plt.grid(True)
plt.show()

plt.figure(figsize=(12,3))
plt.plot(ec.index, dd)
plt.title("Drawdown")
plt.grid(True)
plt.show()

plt.figure(figsize=(12,3))
plt.plot(final["hold_count"].index, final["hold_count"].values)
plt.title("Holdings Count")
plt.grid(True)
plt.show()

# ----------------------------
# OPTIONAL: TRADE LOG
# ----------------------------
print("\nTrade log (head):")
display(final["trade_log"].head(10))
print("\nTrade log (tail):")
display(final["trade_log"].tail(10))
final["trade_log"].to_csv('TL.csv')

