# -*- coding: utf-8 -*-
"""Kriti_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWDuytbW2L2hEEdptlWGKkXSDobYMCuZ
"""

# KRITI 2026
from google.colab import drive
drive.mount('/content/drive')

import subprocess, sys
for pkg in ["yfinance","pandas","numpy","xgboost","matplotlib","scikit-learn"]:
    try: __import__(pkg)
    except ImportError:
        subprocess.check_call([sys.executable,"-m","pip","install","-q",pkg])

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from xgboost import XGBClassifier
import warnings, os, time
warnings.filterwarnings("ignore")
t0 = time.time()

# CONFIGURATION
print("="*60)
print("KRITI 2026")
print("="*60)

TRAIN_START = input("Enter Training Start Date (YYYY-MM-DD) [Default: 2010-01-01]: ").strip() or "2010-01-01"
TRAIN_END   = input("Enter Training End Date (YYYY-MM-DD) [Default: 2019-12-31]: ").strip() or "2019-12-31"
TEST_START  = input("Enter Testing Start Date (YYYY-MM-DD) [Default: 2020-01-01]: ").strip() or "2020-01-01"
TEST_END    = input("Enter Testing End Date (YYYY-MM-DD) [Default: 2025-06-30]: ").strip() or "2025-06-30"

_cap_input = input("Enter Initial Capital [Default: 5000000.0]: ").strip()
INITIAL_CAPITAL     = float(_cap_input) if _cap_input else 5_000_000.0

MAX_HOLDINGS        = 100
COST_PER_SIDE       = 0.00268
ANNUAL_TRADING_DAYS = 252

FWD_HORIZON_DAYS  = 21
TOP_PCTILE        = 0.30
ATR_N             = 21
RETRAIN_FREQ      = 63
MIN_TRAIN_ROWS    = 10_000
MAX_SINGLE_WEIGHT = 0.04
STOP_ATR_MULT     = 3.0
MIN_EXPOSURE      = 0.75
MAX_EXPOSURE      = 1.00
MIN_HOLD_DAYS     = 10
RESCORE_PCTILE    = 0.40
DAILY_BUY_LIMIT   = 25

# UNIVERSE
LARGE_CAP = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","SBIN.NS","BHARTIARTL.NS","ITC.NS","KOTAKBANK.NS",
    "LT.NS","AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "TITAN.NS","ULTRACEMCO.NS","BAJFINANCE.NS","WIPRO.NS","NTPC.NS",
    "POWERGRID.NS","HCLTECH.NS","ONGC.NS","COALINDIA.NS","DIVISLAB.NS",
    "NESTLEIND.NS","TATAMOTORS.NS","TATASTEEL.NS","JSWSTEEL.NS","ADANIENT.NS",
    "BAJAJFINSV.NS","TECHM.NS","DRREDDY.NS","CIPLA.NS","EICHERMOT.NS",
    "APOLLOHOSP.NS","DABUR.NS","BRITANNIA.NS","HEROMOTOCO.NS","BPCL.NS",
]
MID_CAP = [
    "MUTHOOTFIN.NS","PERSISTENT.NS","CUMMINSIND.NS","SCHAEFFLER.NS",
    "COFORGE.NS","LTTS.NS","TRENT.NS","POLYCAB.NS","AUROPHARMA.NS",
    "CROMPTON.NS","DEEPAKNTR.NS","VOLTAS.NS","GODREJPROP.NS","ASTRAL.NS",
    "MAXHEALTH.NS","PAGEIND.NS","PIIND.NS","CONCOR.NS","INDIAMART.NS",
    "IRCTC.NS","METROPOLIS.NS","LALPATHLAB.NS","SYNGENE.NS","ATUL.NS",
    "GLAND.NS","DIXON.NS","ANGELONE.NS","IDFCFIRSTB.NS","SUNDARMFIN.NS",
    "ZOMATO.NS","NYKAA.NS","DELHIVERY.NS","PAYTM.NS","POLICYBZR.NS",
    "CAMPUS.NS","DMART.NS","HDFCAMC.NS","MFSL.NS","CHOLAFIN.NS","ABCAPITAL.NS",
    "FEDERALBNK.NS","BANDHANBNK.NS","RBLBANK.NS","INDIANB.NS","CANBK.NS",
    "BALKRISIND.NS","MRF.NS","EXIDEIND.NS","MOTHERSON.NS",
]
SMALL_CAP = [
    "GRAPHITE.NS","RATEGAIN.NS","BIKAJI.NS","ROUTE.NS","HAPPSTMNDS.NS",
    "LATENTVIEW.NS","KFINTECH.NS","ANANTRAJ.NS","VGUARD.NS","KAYNES.NS",
    "SYRMA.NS","HOMEFIRST.NS","EASEMYTRIP.NS","KPITTECH.NS","MAPMYINDIA.NS",
    "EPIGRAL.NS","MEDPLUS.NS","SENCO.NS","RAJRATAN.NS",
    "SUZLON.NS","INOXWIND.NS","ORIENTELEC.NS","FINEORG.NS","ALKYLAMINE.NS",
    "NAVINFLUOR.NS","CLEAN.NS","AAVAS.NS","APTUS.NS","CREDITACC.NS",
    "RHIM.NS","HLEGLAS.NS","WINDLAS.NS","GLOBUSSPR.NS",
    "JYOTICNC.NS","RATNAMANI.NS","JINDALSAW.NS","WELCORP.NS","MAHSCOOTER.NS",
    "STOVEKRAFT.NS","ZYDUSWELL.NS","TTKPRESTIG.NS",
    "VAIBHAVGBL.NS","THANGAMAYL.NS","KALYANKJIL.NS",
    "WONDERLA.NS","CHALET.NS","LEMONTREE.NS","NUVOCO.NS",
    "KRBL.NS","AVANTIFEED.NS","WATERBASE.NS","SHAKTIPUMP.NS","IGARASHI.NS",
    "QUICKHEAL.NS","TANLA.NS","INTELLECT.NS","MASTEK.NS",
]

ALL_TICKERS = (
    [(t,"largecap") for t in LARGE_CAP] +
    [(t,"midcap")   for t in MID_CAP] +
    [(t,"smallcap") for t in SMALL_CAP]
)

SECTOR_MAP = {
    "RELIANCE.NS":"Energy","ONGC.NS":"Energy","BPCL.NS":"Energy","COALINDIA.NS":"Energy",
    "NTPC.NS":"Energy","POWERGRID.NS":"Energy","SUZLON.NS":"Energy","INOXWIND.NS":"Energy",
    "TCS.NS":"IT","INFY.NS":"IT","WIPRO.NS":"IT","HCLTECH.NS":"IT","TECHM.NS":"IT",
    "PERSISTENT.NS":"IT","COFORGE.NS":"IT","LTTS.NS":"IT","KPITTECH.NS":"IT",
    "MASTEK.NS":"IT","RATEGAIN.NS":"IT","LATENTVIEW.NS":"IT","MAPMYINDIA.NS":"IT",
    "HAPPSTMNDS.NS":"IT","TANLA.NS":"IT","INTELLECT.NS":"IT","DIXON.NS":"IT",
    "HDFCBANK.NS":"Banking","ICICIBANK.NS":"Banking","SBIN.NS":"Banking",
    "KOTAKBANK.NS":"Banking","AXISBANK.NS":"Banking","IDFCFIRSTB.NS":"Banking",
    "FEDERALBNK.NS":"Banking","BANDHANBNK.NS":"Banking","RBLBANK.NS":"Banking",
    "INDIANB.NS":"Banking","CANBK.NS":"Banking",
    "BAJFINANCE.NS":"NBFC","BAJAJFINSV.NS":"NBFC","MUTHOOTFIN.NS":"NBFC",
    "SUNDARMFIN.NS":"NBFC","CHOLAFIN.NS":"NBFC","ABCAPITAL.NS":"NBFC",
    "ANGELONE.NS":"NBFC","HDFCAMC.NS":"NBFC","MFSL.NS":"NBFC",
    "HOMEFIRST.NS":"NBFC","AAVAS.NS":"NBFC","APTUS.NS":"NBFC","CREDITACC.NS":"NBFC",
    "HINDUNILVR.NS":"FMCG","ITC.NS":"FMCG","NESTLEIND.NS":"FMCG",
    "DABUR.NS":"FMCG","BRITANNIA.NS":"FMCG","BIKAJI.NS":"FMCG",
    "KRBL.NS":"FMCG","AVANTIFEED.NS":"FMCG","ZYDUSWELL.NS":"FMCG",
    "TTKPRESTIG.NS":"FMCG","STOVEKRAFT.NS":"FMCG","WATERBASE.NS":"FMCG",
    "SUNPHARMA.NS":"Pharma","DRREDDY.NS":"Pharma","CIPLA.NS":"Pharma",
    "DIVISLAB.NS":"Pharma","AUROPHARMA.NS":"Pharma","GLAND.NS":"Pharma",
    "METROPOLIS.NS":"Pharma","LALPATHLAB.NS":"Pharma","SYNGENE.NS":"Pharma",
    "NAVINFLUOR.NS":"Pharma","ALKYLAMINE.NS":"Pharma","WINDLAS.NS":"Pharma",
    "ROUTE.NS":"Pharma",
    "TATAMOTORS.NS":"Auto","MARUTI.NS":"Auto","EICHERMOT.NS":"Auto",
    "HEROMOTOCO.NS":"Auto","MOTHERSON.NS":"Auto","BALKRISIND.NS":"Auto",
    "MRF.NS":"Auto","EXIDEIND.NS":"Auto","MAHSCOOTER.NS":"Auto","IGARASHI.NS":"Auto",
    "ASIANPAINT.NS":"Paints","PIIND.NS":"Paints","DEEPAKNTR.NS":"Chemicals",
    "ATUL.NS":"Chemicals","FINEORG.NS":"Chemicals","CLEAN.NS":"Chemicals",
    "EPIGRAL.NS":"Chemicals",
    "TATASTEEL.NS":"Metals","JSWSTEEL.NS":"Metals","GRAPHITE.NS":"Metals",
    "RATNAMANI.NS":"Metals","JINDALSAW.NS":"Metals","WELCORP.NS":"Metals","RHIM.NS":"Metals",
    "RAJRATAN.NS":"Metals",
    "LT.NS":"Capital Goods","SCHAEFFLER.NS":"Capital Goods","CUMMINSIND.NS":"Capital Goods",
    "POLYCAB.NS":"Capital Goods","CROMPTON.NS":"Capital Goods","VGUARD.NS":"Capital Goods",
    "KAYNES.NS":"Capital Goods","SYRMA.NS":"Capital Goods","ORIENTELEC.NS":"Capital Goods",
    "SHAKTIPUMP.NS":"Capital Goods","JYOTICNC.NS":"Capital Goods",
    "TITAN.NS":"Jewellery","SENCO.NS":"Jewellery","VAIBHAVGBL.NS":"Jewellery",
    "THANGAMAYL.NS":"Jewellery","KALYANKJIL.NS":"Jewellery",
    "APOLLOHOSP.NS":"Healthcare","MAXHEALTH.NS":"Healthcare","MEDPLUS.NS":"Healthcare",
    "DMART.NS":"Retail","TRENT.NS":"Retail","KALYANKJIL.NS":"Retail",
    "ZOMATO.NS":"Internet","NYKAA.NS":"Internet","DELHIVERY.NS":"Internet",
    "PAYTM.NS":"Internet","POLICYBZR.NS":"Internet","EASEMYTRIP.NS":"Internet",
    "INDIAMART.NS":"Internet","IRCTC.NS":"Internet",
    "ANANTRAJ.NS":"RealEstate","GODREJPROP.NS":"RealEstate",
    "CHALET.NS":"RealEstate","LEMONTREE.NS":"RealEstate",
    "BHARTIARTL.NS":"Telecom","CONCOR.NS":"Logistics","NUVOCO.NS":"Cement",
    "ULTRACEMCO.NS":"Cement","VOLTAS.NS":"Consumer Durables",
    "ASTRAL.NS":"Building Materials","HLEGLAS.NS":"Building Materials",
    "WONDERLA.NS":"Leisure","KFINTECH.NS":"FinTech",
    "CAMPUS.NS":"Footwear","PAGEIND.NS":"Apparel","GLOBUSSPR.NS":"Apparel",
    "ADANIENT.NS":"Conglomerate","QUICKHEAL.NS":"IT",
}

# STEP 1 — DATA LOAD
print("\n"+"="*60)
print("STEP 1 — Loading Data")
print("="*60)

def download_tickers(ticker_list, data_start, data_end):
    frames = []
    failed = []
    for ticker, cap in ticker_list:
        try:
            raw = yf.download(ticker, start=data_start, end=data_end,
                              progress=False, auto_adjust=True)
            if raw.empty or len(raw) < 100:
                failed.append(ticker); continue
            if isinstance(raw.columns, pd.MultiIndex):
                raw.columns = raw.columns.get_level_values(0)
            df = raw[["Open","High","Low","Close","Volume"]].copy()
            df.columns = ["open","high","low","close","volume"]
            df = df.reset_index()
            df.rename(columns={"Date":"tradedate"}, inplace=True)
            df["tradedate"] = pd.to_datetime(df["tradedate"]).dt.tz_localize(None)
            df["fid"]                = ticker
            df["cap_classification"] = cap
            df["in_NSE500"]          = 1 if cap == "largecap" else 0
            df["sector"]             = SECTOR_MAP.get(ticker, "Other")
            df = df.dropna()
            frames.append(df)
        except Exception as e:
            failed.append(ticker)
    if failed:
        print(f"  Skipped {len(failed)} tickers: {failed[:5]}{'...' if len(failed)>5 else ''}")
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()

data_start = (pd.to_datetime(TRAIN_START) - pd.DateOffset(days=300)).strftime("%Y-%m-%d")
print(f"Downloading {len(ALL_TICKERS)} tickers...")
data = download_tickers(ALL_TICKERS, data_start, TEST_END)
data.sort_values(["fid","tradedate"], inplace=True)
data.reset_index(drop=True, inplace=True)
print(f"  Loaded: {data['fid'].nunique()} tickers, {len(data):,} rows")

print("Downloading Nifty 500 benchmark...")
nifty = None
try:
    n5 = yf.download("^CRSLDX", start=TRAIN_START, end=TEST_END,
                     progress=False, auto_adjust=True)
    if isinstance(n5.columns, pd.MultiIndex):
        n5.columns = n5.columns.get_level_values(0)
    nifty = n5[["Close"]].copy()
    nifty.index = pd.to_datetime(nifty.index).tz_localize(None)
    nifty.columns = ["nifty_close"]
    nifty["nifty_ret"] = nifty["nifty_close"].pct_change()
    print(f"  Nifty 500 loaded: {len(nifty)} rows")
except Exception as e:
    print(f"  Nifty 500 failed ({e}), trying ^NSEI...")
    try:
        n5 = yf.download("^NSEI", start=TRAIN_START, end=TEST_END,
                         progress=False, auto_adjust=True)
        if isinstance(n5.columns, pd.MultiIndex):
            n5.columns = n5.columns.get_level_values(0)
        nifty = n5[["Close"]].copy()
        nifty.index = pd.to_datetime(nifty.index).tz_localize(None)
        nifty.columns = ["nifty_close"]
        nifty["nifty_ret"] = nifty["nifty_close"].pct_change()
        print(f"  Nifty (^NSEI) loaded: {len(nifty)} rows")
    except:
        print("  Benchmark unavailable, continuing without it.")

# STEP 2 — FEATURE ENGINEERING
print("\n"+"="*60)
print("STEP 2 — Feature Engineering")
print("="*60)

def calc_atr(high, low, close, n=21):
    prev = close.shift(1)
    tr = pd.concat([high-low,(high-prev).abs(),(low-prev).abs()],axis=1).max(axis=1)
    return tr.ewm(span=n, adjust=False).mean()

rows = []
for fid, g in data.groupby("fid"):
    g = g.copy().reset_index(drop=True)
    g["atr21"]      = calc_atr(g["high"], g["low"], g["close"], ATR_N)
    g["ema50"]      = g["close"].ewm(span=50, adjust=False).mean()
    g["ema200"]     = g["close"].ewm(span=200, adjust=False).mean()
    safe_atr        = g["atr21"].replace(0, np.nan)
    g["dist_ema50"] = (g["close"] - g["ema50"]) / safe_atr
    g["dist_ema200"]= (g["close"] - g["ema200"]) / safe_atr
    g["ret_5"]      = g["close"].pct_change(5)
    g["ret_21"]     = g["close"].pct_change(21)
    g["ret_63"]     = g["close"].pct_change(63)
    vol_ma20        = g["volume"].rolling(20, min_periods=5).mean()
    g["vol_ratio"]  = np.log1p(g["volume"] / vol_ma20.replace(0, np.nan))
    roll_h          = g["high"].rolling(21).max()
    roll_l          = g["low"].rolling(21).min()
    g["dist_pivot"] = (g["close"] - (roll_h+roll_l+g["close"])/3) / safe_atr
    hi52            = g["high"].rolling(252, min_periods=60).max()
    g["hi52w_prox"] = g["close"] / hi52.replace(0, np.nan)
    g["pullback"]   = ((g["ret_21"]>0) & (g["ret_5"]<0)).astype(int)
    g["trend_cons"] = g["close"].diff().gt(0).rolling(21).mean()
    g["fwd_ret"]    = g["close"].shift(-FWD_HORIZON_DAYS) / g["close"] - 1.0
    rows.append(g)

panel = pd.concat(rows, ignore_index=True)

print("Computing sector momentum...")
sector_ret = (
    panel.groupby(["tradedate","sector"])["ret_21"]
    .mean().reset_index()
    .rename(columns={"ret_21":"sector_ret21"})
)
market_ret = (
    panel.groupby("tradedate")["ret_21"]
    .mean().reset_index()
    .rename(columns={"ret_21":"market_ret21"})
)
sector_ret = sector_ret.merge(market_ret, on="tradedate")
sector_ret["sector_mom"] = sector_ret["sector_ret21"] - sector_ret["market_ret21"]
panel = panel.merge(sector_ret[["tradedate","sector","sector_mom"]],
                    on=["tradedate","sector"], how="left")

print("Computing dual breadth (rolling percentile rank)...")
panel["above_ema50"] = (panel["close"] > panel["ema50"]).astype(int)

b1_raw = (panel[panel["in_NSE500"]==1]
          .groupby("tradedate")["above_ema50"].mean()
          .reset_index().rename(columns={"above_ema50":"breadth_nse500_raw"}))

b2_raw = (panel.groupby("tradedate")["above_ema50"]
          .mean().reset_index().rename(columns={"above_ema50":"breadth_universe_raw"}))

b1_raw = b1_raw.sort_values("tradedate")
b1_raw["breadth_nse500"] = (
    b1_raw["breadth_nse500_raw"]
    .rolling(252, min_periods=63)
    .apply(lambda x: pd.Series(x).rank(pct=True).iloc[-1], raw=False)
)

b2_raw = b2_raw.sort_values("tradedate")
b2_raw["breadth_universe"] = (
    b2_raw["breadth_universe_raw"]
    .rolling(252, min_periods=63)
    .apply(lambda x: pd.Series(x).rank(pct=True).iloc[-1], raw=False)
)

panel = panel.merge(b1_raw[["tradedate","breadth_nse500"]], on="tradedate", how="left")
panel = panel.merge(b2_raw[["tradedate","breadth_universe"]], on="tradedate", how="left")

for col in ["breadth_nse500","breadth_universe"]:
    panel[col] = panel[col].ffill().fillna(0.5)
    panel[col] = panel.groupby("fid")[col].transform(
        lambda x: x.ewm(span=10, adjust=False).mean())

print("Assigning labels...")
panel["label"] = panel.groupby("tradedate")["fwd_ret"].transform(
    lambda x: (x >= x.quantile(1-TOP_PCTILE)).astype(float))
panel.loc[panel["fwd_ret"].isna(), "label"] = np.nan

FEATURES = [
    "dist_ema50","dist_ema200","ret_5","ret_21","ret_63",
    "vol_ratio","dist_pivot","hi52w_prox","pullback",
    "trend_cons","sector_mom","breadth_nse500","breadth_universe",
]
panel = panel.dropna(subset=FEATURES).copy()
panel.sort_values(["tradedate","fid"], inplace=True)
panel.reset_index(drop=True, inplace=True)
print(f"Panel: {panel.shape} | Tickers: {panel['fid'].nunique()}")

# STEP 3 — WALK-FORWARD TRAINING
print("\n"+"="*60)
print("STEP 3 — Walk-Forward Training")
print("="*60)

def train_model(train_data, features):
    model = XGBClassifier(
        n_estimators=400, max_depth=4, learning_rate=0.03,
        subsample=0.75, colsample_bytree=0.65,
        min_child_weight=40, gamma=1.5, reg_lambda=2.5,
        eval_metric="logloss", random_state=42,
        n_jobs=-1, use_label_encoder=False,
    )
    X = train_data[features].fillna(0).values
    y = train_data["label"].values
    model.fit(X, y)
    return model

test_dates = sorted(panel[panel["tradedate"]>=pd.to_datetime(TEST_START)]["tradedate"].unique())
model_store = {}
idx = 0
while idx < len(test_dates):
    rd = test_dates[idx]
    cutoff = pd.to_datetime(rd) - pd.DateOffset(days=FWD_HORIZON_DAYS)
    pool = panel[(panel["tradedate"]<cutoff) & panel["label"].notna()]
    if len(pool) >= MIN_TRAIN_ROWS:
        print(f"  Retrain @ {pd.to_datetime(rd).date()} | rows={len(pool):,}")
        model_store[rd] = train_model(pool, FEATURES)
    idx += RETRAIN_FREQ

base_cutoff = pd.to_datetime(TRAIN_END) - pd.DateOffset(days=FWD_HORIZON_DAYS)
base_model = train_model(
    panel[(panel["tradedate"]<=base_cutoff) & panel["label"].notna()],
    FEATURES)
print(f"  Base model ready. Total retrains: {len(model_store)}")

# STEP 4 — BACKTEST ENGINE
def run_backtest(df, start_date, end_date):
    df_p = df[(df["tradedate"]>=pd.to_datetime(start_date)) &
              (df["tradedate"]<=pd.to_datetime(end_date))].copy()

    dates   = sorted(df_p["tradedate"].unique())
    by_date = {d: g for d, g in df_p.groupby("tradedate")}

    cash         = INITIAL_CAPITAL
    positions    = {}
    equity_curve = []
    trade_log    = []
    pos_counts   = []
    active_model = base_model

    for i in range(len(dates)-1):
        day_T  = dates[i]
        day_T1 = dates[i+1]
        data_T  = by_date.get(day_T)
        data_T1 = by_date.get(day_T1)
        if data_T is None or data_T1 is None: continue

        if day_T in model_store:
            active_model = model_store[day_T]

        row_T  = {r.fid: r for r in data_T.itertuples(index=False)}
        row_T1 = {r.fid: r for r in data_T1.itertuples(index=False)}

        stock_val = sum(
            pos["shares"]*(row_T[f].close if f in row_T else pos["last_close"])
            for f, pos in positions.items())
        for f, pos in positions.items():
            if f in row_T: pos["last_close"] = row_T[f].close
        equity = cash + stock_val
        equity_curve.append({"date":day_T,"equity":equity,"cash":cash})

        held_scores = {}
        for fid, pos in positions.items():
            if fid in row_T:
                st = row_T[fid]
                fv = np.array([[getattr(st,f,0.0) for f in FEATURES]])
                held_scores[fid] = active_model.predict_proba(fv)[0,1]

        live_score_threshold = (
            np.percentile(list(held_scores.values()), RESCORE_PCTILE*100)
            if held_scores else 0.0
        )

        signals_to_sell = []
        for fid, pos in positions.items():
            if fid not in row_T:
                signals_to_sell.append(fid); continue
            st = row_T[fid]

            if st.close > pos["highest_close"]:
                pos["highest_close"] = st.close
                pos["stop_price"]    = st.close - pos["atr"]*STOP_ATR_MULT

            hit_stop     = (pos["hold_days"] >= MIN_HOLD_DAYS and
                            st.close < pos["stop_price"])
            rescore_exit = (pos["hold_days"] >= MIN_HOLD_DAYS and
                            held_scores.get(fid, 1.0) < live_score_threshold)

            if hit_stop or rescore_exit:
                signals_to_sell.append(fid)
            else:
                pos["hold_days"] += 1

        scored = []
        for st in data_T.itertuples(index=False):
            fid = st.fid
            if fid in positions or fid not in row_T1: continue
            fv    = np.array([[getattr(st,f,0.0) for f in FEATURES]])
            score = active_model.predict_proba(fv)[0,1]
            scored.append((fid, score, float(getattr(st,"atr21",1.0))))

        buy_candidates = []
        if scored:
            thr = np.percentile([s[1] for s in scored], (1-TOP_PCTILE)*100)
            buy_candidates = sorted(
                [(f,s,a) for f,s,a in scored if s>=thr],
                key=lambda x: x[1], reverse=True
            )
            open_slots = MAX_HOLDINGS - len(positions) + len(signals_to_sell)
            buy_candidates = buy_candidates[:min(DAILY_BUY_LIMIT, open_slots)]

        for fid in signals_to_sell:
            if fid not in row_T1: continue
            st1      = row_T1[fid]
            ep       = (st1.open+st1.high+st1.low+st1.close)/4.0
            proceeds = positions[fid]["shares"]*ep*(1.0-COST_PER_SIDE)
            cash    += proceeds
            trade_log.append({
                "date":day_T1,"fid":fid,"action":"SELL",
                "shares":positions[fid]["shares"],"price":ep,
                "hold_days":positions[fid]["hold_days"],
                "pnl_pct":(ep/positions[fid]["entry_price"]-1)*100,
            })
            del positions[fid]

        b_nse   = float(data_T["breadth_nse500"].iloc[0])
        b_uni   = float(data_T["breadth_universe"].iloc[0])
        bear    = (b_nse < 0.40) and (b_uni < 0.40)
        eff_min = 0.55 if bear else MIN_EXPOSURE
        eff_max = 0.85 if bear else MAX_EXPOSURE
        target_exp = eff_min + (eff_max - eff_min) * b_uni

        invested = sum(p["shares"]*p["last_close"] for p in positions.values())
        gap      = max(0.0, target_exp * equity - invested)
        avail    = min(gap, cash)

        if buy_candidates and avail > 500:
            inv_atrs  = [1.0/max(a,1e-6) for _,_,a in buy_candidates]
            total_inv = sum(inv_atrs)
            for (fid,score,atr), inv_a in zip(buy_candidates, inv_atrs):
                if fid not in row_T1 or len(positions)>=MAX_HOLDINGS: break
                wt     = inv_a / total_inv
                budget = min(avail*wt, equity*MAX_SINGLE_WEIGHT)
                st1    = row_T1[fid]
                ep     = (st1.open+st1.high+st1.low+st1.close)/4.0
                gross  = ep*(1.0+COST_PER_SIDE)
                shares = int(budget//gross)
                if shares<1 or cash<shares*gross: continue
                cash -= shares*gross
                positions[fid] = {
                    "shares":shares,"entry_price":ep,"last_close":ep,
                    "highest_close":ep,"atr":atr,
                    "stop_price":ep-atr*STOP_ATR_MULT,"hold_days":0,
                }
                trade_log.append({
                    "date":day_T1,"fid":fid,"action":"BUY",
                    "shares":shares,"price":ep,
                    "hold_days":0,"pnl_pct":0.0,
                })

        pos_counts.append({"date":day_T,"n_pos":len(positions),
                            "breadth_nse500":b_nse,"breadth_universe":b_uni})

    return (pd.DataFrame(equity_curve),
            pd.DataFrame(trade_log),
            pd.DataFrame(pos_counts))

# STEP 5 — BASE RUN
print("\n"+"="*60)
print("STEP 5 — Base Backtest")
print("="*60)
eq, trades, poscnt = run_backtest(panel, TEST_START, TEST_END)

# STEP 6 — PERFORMANCE METRICS
def metrics(eq_df, trades_df, label, nifty_df=None):
    if eq_df.empty: return {}
    eq_df = eq_df.copy().set_index("date").sort_index()
    eq_df["dr"] = eq_df["equity"].pct_change()
    s, e  = eq_df["equity"].iloc[0], eq_df["equity"].iloc[-1]
    yrs   = max((eq_df.index[-1]-eq_df.index[0]).days/365.25, 1e-9)
    cagr  = (e/s)**(1/yrs)-1
    vol   = eq_df["dr"].std()*np.sqrt(ANNUAL_TRADING_DAYS)
    sharpe= cagr/vol if vol>0 else 0
    rm    = eq_df["equity"].cummax()
    mdd   = ((eq_df["equity"]-rm)/rm).min()
    calmar= cagr/abs(mdd) if mdd!=0 else 0
    neg   = eq_df["dr"][eq_df["dr"]<0]
    sortino = cagr/(neg.std()*np.sqrt(ANNUAL_TRADING_DAYS)) if len(neg)>0 else 0

    if not trades_df.empty and "pnl_pct" in trades_df.columns:
        sells  = trades_df[trades_df["action"]=="SELL"]["pnl_pct"].dropna()
        winrt  = (sells>0).mean() if len(sells)>0 else np.nan
        avg_w  = sells[sells>0].mean() if (sells>0).any() else 0
        avg_l  = sells[sells<0].mean() if (sells<0).any() else 0
        pf     = abs(avg_w/avg_l) if avg_l!=0 else np.nan
    else:
        winrt=avg_w=avg_l=pf=np.nan

    m = dict(label=label,cagr=cagr,vol=vol,sharpe=sharpe,mdd=mdd,
             calmar=calmar,sortino=sortino,winrate=winrt,
             profit_factor=pf,avg_win=avg_w,avg_loss=avg_l)

    if nifty_df is not None and not nifty_df.empty:
        common = eq_df.index.intersection(nifty_df.index)
        if len(common)>20:
            sr = eq_df.loc[common,"dr"].fillna(0)
            br = nifty_df.loc[common,"nifty_ret"].fillna(0)
            ex = sr-br
            ir = ex.mean()/ex.std()*np.sqrt(ANNUAL_TRADING_DAYS) if ex.std()>0 else 0
            up_c  = sr[br>0].mean()/br[br>0].mean() if br[br>0].mean()!=0 else np.nan
            dn_c  = sr[br<0].mean()/br[br<0].mean() if br[br<0].mean()!=0 else np.nan
            bc    = nifty_df.loc[common,"nifty_close"]
            byrs  = (common[-1]-common[0]).days/365.25
            bcagr = (bc.iloc[-1]/bc.iloc[0])**(1/byrs)-1
            m.update(ir=ir,up_capture=up_c,down_capture=dn_c,bench_cagr=bcagr)
            roll = {}
            for w,lbl in [(252,"1yr"),(756,"3yr"),(1260,"5yr")]:
                if len(ex)>w:
                    rs = ex.rolling(w).sum()*(ANNUAL_TRADING_DAYS/w)
                    roll[lbl]={"avg":rs.dropna().mean(),"worst":rs.dropna().min()}
            m["rolling"]=roll
    return m

def print_metrics(m):
    if not m: return
    print(f"\n{'─'*58}")
    print(f"  {m['label']}")
    print(f"{'─'*58}")
    print(f"  CAGR              : {m['cagr']*100:>8.2f}%"
          + (f"  (Nifty: {m['bench_cagr']*100:.2f}%)" if 'bench_cagr' in m else ""))
    print(f"  Volatility        : {m['vol']*100:>8.2f}%")
    print(f"  Sharpe            : {m['sharpe']:>8.2f}")
    print(f"  Sortino           : {m['sortino']:>8.2f}")
    print(f"  Max Drawdown      : {m['mdd']*100:>8.2f}%")
    print(f"  Calmar            : {m['calmar']:>8.2f}")
    print(f"  Win Rate          : {m.get('winrate',float('nan'))*100:>8.1f}%")
    print(f"  Profit Factor     : {m.get('profit_factor',float('nan')):>8.2f}")
    if "ir" in m:
        print(f"  Info Ratio        : {m['ir']:>8.2f}")
        print(f"  Up-Capture        : {m.get('up_capture',float('nan'))*100:>8.1f}%")
        print(f"  Down-Capture      : {m.get('down_capture',float('nan'))*100:>8.1f}%")
    if m.get("rolling"):
        print(f"  Rolling vs Nifty500:")
        for w,v in m["rolling"].items():
            print(f"    {w:>4s}: avg {v['avg']*100:+.2f}%  worst {v['worst']*100:+.2f}%")

nifty_oos = nifty[nifty.index>=pd.to_datetime(TEST_START)] if nifty is not None else None
base_m    = metrics(eq, trades, "BASE RUN — OOS", nifty_oos)
print_metrics(base_m)

print("\n  Per-year performance:")
print(f"  {'Year':<6} {'Strat':>8} {'Nifty':>8} {'Alpha':>8} {'MaxDD':>8}")
print(f"  {'─'*42}")
if not eq.empty:
    eq_y = eq.copy().set_index("date")
    for yr in range(int(TEST_START[:4]), int(TEST_END[:4])+1):
        yr_eq = eq_y[eq_y.index.year==yr]["equity"]
        if len(yr_eq)<5: continue
        ret_s = yr_eq.iloc[-1]/yr_eq.iloc[0]-1
        rm    = yr_eq.cummax()
        dd    = ((yr_eq-rm)/rm).min()
        ret_b = np.nan
        if nifty_oos is not None:
            yr_n = nifty_oos[nifty_oos.index.year==yr]["nifty_close"]
            if len(yr_n)>5:
                ret_b = yr_n.iloc[-1]/yr_n.iloc[0]-1
        alpha = ret_s-ret_b if not np.isnan(ret_b) else np.nan
        print(f"  {yr:<6} {ret_s*100:>8.1f}% {ret_b*100:>8.1f}% "
              f"{alpha*100:>+8.1f}% {dd*100:>8.1f}%")

# STEP 7 — CHARTS (Base run — 5 panels)
print("\n"+"="*60)
print("STEP 7 — Generating Base Charts")
print("="*60)

OUTPUT_DIR = "/content/drive/MyDrive/kriti_results"
os.makedirs(OUTPUT_DIR, exist_ok=True)

fig = plt.figure(figsize=(16, 18))
gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.45, wspace=0.32)

ax1 = fig.add_subplot(gs[0, :])
if not eq.empty:
    eq_plot = eq.set_index("date")
    ax1.plot(eq_plot.index, eq_plot["equity"]/1e5,
             color="#2563EB", lw=2.0, label="Kriti v7 Strategy", zorder=5)
    ax1.fill_between(eq_plot.index, eq_plot["equity"]/1e5, alpha=0.08, color="#2563EB")
    if nifty_oos is not None:
        common = eq_plot.index.intersection(nifty_oos.index)
        if len(common):
            nb = (nifty_oos.loc[common,"nifty_close"] /
                  nifty_oos.loc[common[0],"nifty_close"] *
                  (eq_plot.loc[common[0],"equity"]/1e5))
            ax1.plot(common, nb, color="#DC2626", lw=1.4,
                     linestyle="-.", label="Nifty 500 rebased", alpha=0.85)
    ax1.set_title("Equity Curve vs Nifty 500 Benchmark", fontweight="bold", fontsize=11)
    ax1.set_ylabel("NAV (₹ lakhs)")
    ax1.legend(loc="upper left", fontsize=9, framealpha=0.6)
    ax1.grid(True, alpha=0.25)

ax2 = fig.add_subplot(gs[1, :])
if not eq.empty:
    ep = eq.set_index("date")["equity"]
    dd = (ep - ep.cummax())/ep.cummax()*100
    ax2.fill_between(dd.index, dd, 0, color="#DC2626", alpha=0.35)
    ax2.plot(dd.index, dd, color="#DC2626", lw=0.9)
    ax2.set_title("Strategy Drawdown", fontweight="bold", fontsize=11)
    ax2.set_ylabel("Drawdown (%)")
    ax2.grid(True, alpha=0.25)

ax3 = fig.add_subplot(gs[2, 0])
if not eq.empty:
    dr = eq.set_index("date")["equity"].pct_change()
    rs = dr.rolling(252).mean()/dr.rolling(252).std()*np.sqrt(252)
    ax3.plot(rs.index, rs, color="#7C3AED", lw=1.4)
    ax3.axhline(0, color="gray", lw=0.8, ls="--")
    ax3.axhline(1, color="#059669", lw=0.8, ls=":", label="Sharpe = 1")
    ax3.set_title("Rolling 1-year Sharpe", fontweight="bold", fontsize=11)
    ax3.legend(fontsize=8)
    ax3.grid(True, alpha=0.25)

ax4 = fig.add_subplot(gs[2, 1])
if not trades.empty and "pnl_pct" in trades.columns:
    sells = trades[trades["action"]=="SELL"]["pnl_pct"].dropna()
    if len(sells):
        ax4.hist(sells, bins=50, color="#2563EB", alpha=0.65, edgecolor="white")
        ax4.axvline(0, color="#EF4444", lw=1.5, ls="--")
        ax4.axvline(sells.mean(), color="#059669", lw=1.5,
                    label=f"Mean {sells.mean():.1f}%")
        ax4.set_title("Trade P&L Distribution", fontweight="bold", fontsize=11)
        ax4.set_xlabel("P&L per trade (%)")
        ax4.legend(fontsize=8)
        ax4.grid(True, alpha=0.25)

fig.suptitle("Kriti 2026 — Strategy v7.0.1  |  Base Run",
             fontsize=13, fontweight="bold", y=0.998)
plt.savefig(os.path.join(OUTPUT_DIR, "kriti2026_v7_report.png"), dpi=150, bbox_inches="tight")
plt.close()
print("  Chart saved → kriti2026_v7_report.png")

if not trades.empty:
    trades.to_csv(os.path.join(OUTPUT_DIR, "kriti2026_v7_tradelog.csv"), index=False)
    print("  Trade log saved → kriti2026_v7_tradelog.csv")

# STEP 8 — STRESS TESTS
print("\n"+"="*60)
print("STEP 8 — Stress Tests")
print("="*60)

st0 = time.time()

def run_stress_backtest(df, start_date, end_date,
                        cost_override=None,
                        stop_mult_override=None,
                        min_exp_override=None,
                        universe_filter=None,
                        crash_dates=None):

    cost      = cost_override      if cost_override      is not None else COST_PER_SIDE
    stop_mult = stop_mult_override if stop_mult_override is not None else STOP_ATR_MULT
    min_exp   = min_exp_override   if min_exp_override   is not None else MIN_EXPOSURE

    df_p = df[(df["tradedate"] >= pd.to_datetime(start_date)) &
              (df["tradedate"] <= pd.to_datetime(end_date))].copy()
    if universe_filter:
        df_p = df_p[df_p["cap_classification"].isin(universe_filter)]

    dates   = sorted(df_p["tradedate"].unique())
    by_date = {d: g for d, g in df_p.groupby("tradedate")}

    cash         = INITIAL_CAPITAL
    positions    = {}
    equity_curve = []
    trade_log    = []
    active_model = base_model

    def in_crash(d):
        if not crash_dates: return False
        for cs, ce in crash_dates:
            if pd.to_datetime(cs) <= d <= pd.to_datetime(ce):
                return True
        return False

    for i in range(len(dates) - 1):
        day_T  = dates[i]
        day_T1 = dates[i + 1]
        data_T  = by_date.get(day_T)
        data_T1 = by_date.get(day_T1)
        if data_T is None or data_T1 is None: continue

        if day_T in model_store:
            active_model = model_store[day_T]

        row_T  = {r.fid: r for r in data_T.itertuples(index=False)}
        row_T1 = {r.fid: r for r in data_T1.itertuples(index=False)}

        stock_val = sum(
            pos["shares"] * (row_T[f].close if f in row_T else pos["last_close"])
            for f, pos in positions.items())
        for f, pos in positions.items():
            if f in row_T: pos["last_close"] = row_T[f].close
        equity = cash + stock_val
        equity_curve.append({"date": day_T, "equity": equity})

        held_scores = {}
        for fid, pos in positions.items():
            if fid in row_T:
                st = row_T[fid]
                fv = np.array([[getattr(st, f, 0.0) for f in FEATURES]])
                held_scores[fid] = active_model.predict_proba(fv)[0, 1]

        live_score_threshold = (
            np.percentile(list(held_scores.values()), RESCORE_PCTILE * 100)
            if held_scores else 0.0
        )

        signals_to_sell = []
        for fid, pos in positions.items():
            if fid not in row_T:
                signals_to_sell.append(fid); continue
            st = row_T[fid]

            if in_crash(day_T):
                signals_to_sell.append(fid); continue

            if st.close > pos["highest_close"]:
                pos["highest_close"] = st.close
                pos["stop_price"]    = st.close - pos["atr"] * stop_mult

            hit_stop     = (pos["hold_days"] >= MIN_HOLD_DAYS and
                            st.close < pos["stop_price"])
            rescore_exit = (pos["hold_days"] >= MIN_HOLD_DAYS and
                            held_scores.get(fid, 1.0) < live_score_threshold)

            if hit_stop or rescore_exit:
                signals_to_sell.append(fid)
            else:
                pos["hold_days"] += 1

        scored = []
        if not in_crash(day_T):
            for st in data_T.itertuples(index=False):
                fid = st.fid
                if fid in positions or fid not in row_T1: continue
                fv    = np.array([[getattr(st, f, 0.0) for f in FEATURES]])
                score = active_model.predict_proba(fv)[0, 1]
                scored.append((fid, score, float(getattr(st, "atr21", 1.0))))

        buy_candidates = []
        if scored:
            thr = np.percentile([s[1] for s in scored], (1 - TOP_PCTILE) * 100)
            buy_candidates = sorted(
                [(f, s, a) for f, s, a in scored if s >= thr],
                key=lambda x: x[1], reverse=True
            )
            open_slots = MAX_HOLDINGS - len(positions) + len(signals_to_sell)
            buy_candidates = buy_candidates[:min(DAILY_BUY_LIMIT, open_slots)]

        for fid in signals_to_sell:
            if fid not in row_T1: continue
            st1      = row_T1[fid]
            ep       = (st1.open + st1.high + st1.low + st1.close) / 4.0
            proceeds = positions[fid]["shares"] * ep * (1.0 - cost)
            cash    += proceeds
            trade_log.append({
                "date": day_T1, "fid": fid, "action": "SELL",
                "shares": positions[fid]["shares"], "price": ep,
                "hold_days": positions[fid]["hold_days"],
                "pnl_pct": (ep / positions[fid]["entry_price"] - 1) * 100,
            })
            del positions[fid]

        b_nse  = float(data_T["breadth_nse500"].iloc[0])
        b_uni  = float(data_T["breadth_universe"].iloc[0])
        bear   = (b_nse < 0.40) and (b_uni < 0.40)
        eff_min = 0.55 if bear else min_exp
        eff_max = 0.85 if bear else MAX_EXPOSURE
        target_exp = eff_min + (eff_max - eff_min) * b_uni

        invested = sum(p["shares"] * p["last_close"] for p in positions.values())
        gap   = max(0.0, target_exp * equity - invested)
        avail = min(gap, cash)

        if buy_candidates and avail > 500:
            inv_atrs  = [1.0 / max(a, 1e-6) for _, _, a in buy_candidates]
            total_inv = sum(inv_atrs)
            for (fid, score, atr), inv_a in zip(buy_candidates, inv_atrs):
                if fid not in row_T1 or len(positions) >= MAX_HOLDINGS: break
                wt     = inv_a / total_inv
                budget = min(avail * wt, equity * MAX_SINGLE_WEIGHT)
                st1    = row_T1[fid]
                ep     = (st1.open + st1.high + st1.low + st1.close) / 4.0
                gross  = ep * (1.0 + cost)
                shares = int(budget // gross)
                if shares < 1 or cash < shares * gross: continue
                cash -= shares * gross
                positions[fid] = {
                    "shares": shares, "entry_price": ep, "last_close": ep,
                    "highest_close": ep, "atr": atr,
                    "stop_price": ep - atr * stop_mult, "hold_days": 0,
                }

    return pd.DataFrame(equity_curve), pd.DataFrame(trade_log)


def stress_metrics(eq_df, trades_df, label):
    if eq_df.empty: return {}
    eq_df = eq_df.copy().set_index("date").sort_index()
    eq_df["dr"] = eq_df["equity"].pct_change()
    s, e  = eq_df["equity"].iloc[0], eq_df["equity"].iloc[-1]
    yrs   = max((eq_df.index[-1] - eq_df.index[0]).days / 365.25, 1e-9)
    cagr  = (e / s) ** (1 / yrs) - 1
    vol   = eq_df["dr"].std() * np.sqrt(252)
    sharpe= cagr / vol if vol > 0 else 0
    rm    = eq_df["equity"].cummax()
    mdd   = ((eq_df["equity"] - rm) / rm).min()
    calmar= cagr / abs(mdd) if mdd != 0 else 0
    neg   = eq_df["dr"][eq_df["dr"] < 0]
    sortino = cagr / (neg.std() * np.sqrt(252)) if len(neg) > 0 else 0
    if not trades_df.empty and "pnl_pct" in trades_df.columns:
        sells = trades_df[trades_df["action"] == "SELL"]["pnl_pct"].dropna()
        winrt = (sells > 0).mean() if len(sells) > 0 else np.nan
    else:
        winrt = np.nan
    return dict(label=label, cagr=cagr, vol=vol, sharpe=sharpe,
                mdd=mdd, calmar=calmar, sortino=sortino, winrate=winrt,
                eq=eq_df)


# Run all 10 stress scenarios
stress_results = {}
stress_equity_curves = {}

scenarios = [
    ("S1: 2× costs",        dict(cost_override=COST_PER_SIDE * 2)),
    ("S2: 5× costs",        dict(cost_override=COST_PER_SIDE * 5)),
    ("S3: Tight stops",     dict(stop_mult_override=1.5)),
    ("S4: Wide stops",      dict(stop_mult_override=4.0)),
    ("S5: Low exposure",    dict(min_exp_override=0.55)),
    ("S6: Large-cap only",  dict(universe_filter=["largecap"])),
    ("S7: Small/mid only",  dict(universe_filter=["midcap", "smallcap"])),
    ("S8: COVID crash",     dict(crash_dates=[("2020-03-01", "2020-04-30")])),
    ("S9: 2022 rate shock", dict(crash_dates=[("2022-01-01", "2022-06-30")])),
    ("S10: Both crashes",   dict(crash_dates=[("2020-03-01", "2020-04-30"),
                                              ("2022-01-01", "2022-06-30")])),
]

for name, kwargs in scenarios:
    print(f"  Running {name}...")
    eq_s, tr_s = run_stress_backtest(panel, TEST_START, TEST_END, **kwargs)
    m = stress_metrics(eq_s, tr_s, name)
    stress_results[name] = m
    stress_equity_curves[name] = eq_s

print("\n  All scenarios complete.")

# Print summary table
base_cagr = base_m.get("cagr", 0)

print("\n" + "="*60)
print("STRESS TEST SUMMARY")
print("="*60)
print(f"  {'Scenario':<22} {'CAGR':>7} {'Sharpe':>8} {'MaxDD':>8} {'vs Base':>9} {'WinRate':>8}")
print("  " + "─"*66)
for name, m in stress_results.items():
    if not m: continue
    delta = m.get("cagr", 0) - base_cagr
    wr    = m.get("winrate", float("nan"))
    print(f"  {name:<22} {m['cagr']*100:>6.1f}%"
          f" {m['sharpe']:>8.2f}"
          f" {m['mdd']*100:>7.1f}%"
          f" {delta*100:>+8.1f}%"
          f" {wr*100:>7.1f}%")

print(f"\n  {'BASE RUN':<22} {base_cagr*100:>6.1f}%"
      f" {base_m.get('sharpe', 0):>8.2f}"
      f" {base_m.get('mdd', 0)*100:>7.1f}%"
      f"        —"
      f" {base_m.get('winrate', float('nan'))*100:>7.1f}%")

# Cost sensitivity sweep
print("\n" + "="*60)
print("TRANSACTION COST SENSITIVITY")
print("="*60)
print(f"  {'Cost/side':>12} {'CAGR':>8} {'Sharpe':>8} {'MaxDD':>8}")
print("  " + "─"*42)

cost_results = []
for mult in [0.5, 1.0, 1.5, 2.0, 3.0, 5.0]:
    c = COST_PER_SIDE * mult
    eq_c, tr_c = run_stress_backtest(panel, TEST_START, TEST_END,
                                     cost_override=c)
    mc = stress_metrics(eq_c, tr_c, "")
    cost_results.append((mult, c, mc))
    tag = " ← base" if mult == 1.0 else ""
    print(f"  {c*100:>11.4f}%  {mc['cagr']*100:>7.1f}%"
          f"  {mc['sharpe']:>7.2f}  {mc['mdd']*100:>7.1f}%{tag}")

# Stress charts
print("\n" + "="*60)
print("STEP 9 — Generating Stress Charts")
print("="*60)

fig = plt.figure(figsize=(18, 20))
gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.42, wspace=0.30)

ax1 = fig.add_subplot(gs[0, :])
eq_base = eq.set_index("date") if not eq.empty else pd.DataFrame()

color_map = {
    "S1: 2× costs":        ("#94A3B8", "--"),
    "S2: 5× costs":        ("#EF4444", "--"),
    "S3: Tight stops":     ("#F59E0B", ":"),
    "S4: Wide stops":      ("#10B981", ":"),
    "S5: Low exposure":    ("#8B5CF6", "-."),
    "S6: Large-cap only":  ("#06B6D4", "-."),
    "S7: Small/mid only":  ("#F97316", "-"),
    "S8: COVID crash":     ("#EC4899", "--"),
    "S9: 2022 rate shock": ("#6366F1", "--"),
    "S10: Both crashes":   ("#84CC16", "-"),
}

if not eq_base.empty:
    ax1.plot(eq_base.index, eq_base["equity"] / 1e5,
             color="#2563EB", lw=2.5, label="Base strategy", zorder=10)
    ax1.fill_between(eq_base.index, eq_base["equity"] / 1e5,
                     alpha=0.07, color="#2563EB")

for name, eq_s in stress_equity_curves.items():
    if eq_s.empty: continue
    col, ls = color_map.get(name, ("#888888", "--"))
    es = eq_s.set_index("date")
    ax1.plot(es.index, es["equity"] / 1e5, lw=0.9, alpha=0.7,
             linestyle=ls, color=col, label=name)

if nifty_oos is not None and not eq_base.empty:
    common = eq_base.index.intersection(nifty_oos.index)
    if len(common):
        nb = (nifty_oos.loc[common, "nifty_close"] /
              nifty_oos.loc[common[0], "nifty_close"] *
              (eq_base.loc[common[0], "equity"] / 1e5))
        ax1.plot(common, nb, color="#DC2626", lw=1.8,
                 linestyle="-.", label="Nifty 500 rebased", alpha=0.9, zorder=9)

ax1.set_title("Equity Curves — Base vs All Stress Scenarios",
              fontweight="bold", fontsize=11)
ax1.set_ylabel("NAV (₹ lakhs)")
ax1.legend(loc="upper left", fontsize=7, framealpha=0.6, ncol=2)
ax1.grid(True, alpha=0.25)

ax2 = fig.add_subplot(gs[1, 0])
names_bar  = list(stress_results.keys())
cagrs_bar  = [stress_results[n]["cagr"] * 100 for n in names_bar]
colors_bar = ["#EF4444" if c < base_cagr * 100 else "#3B82F6" for c in cagrs_bar]

bars = ax2.barh(range(len(names_bar)), cagrs_bar,
                color=colors_bar, alpha=0.75, height=0.6)
ax2.axvline(base_cagr * 100, color="#059669", lw=1.8, ls="--",
            label=f"Base {base_cagr*100:.1f}%")
ax2.set_yticks(range(len(names_bar)))
ax2.set_yticklabels([n.split(":")[1].strip() for n in names_bar], fontsize=8)
ax2.set_xlabel("CAGR (%)")
ax2.set_title("Stress CAGR vs Base", fontweight="bold", fontsize=11)
ax2.legend(fontsize=8)
ax2.grid(True, alpha=0.25, axis="x")
for bar, val in zip(bars, cagrs_bar):
    ax2.text(val + 0.3, bar.get_y() + bar.get_height()/2,
             f"{val:.1f}%", va="center", fontsize=7.5)

ax3 = fig.add_subplot(gs[1, 1])
sharpes   = [stress_results[n]["sharpe"] for n in names_bar]
base_sh   = base_m.get("sharpe", 0)
col_sh    = ["#EF4444" if s < base_sh else "#3B82F6" for s in sharpes]

bars2 = ax3.barh(range(len(names_bar)), sharpes,
                 color=col_sh, alpha=0.75, height=0.6)
ax3.axvline(base_sh, color="#059669", lw=1.8, ls="--",
            label=f"Base {base_sh:.2f}")
ax3.set_yticks(range(len(names_bar)))
ax3.set_yticklabels([n.split(":")[1].strip() for n in names_bar], fontsize=8)
ax3.set_xlabel("Sharpe ratio")
ax3.set_title("Stress Sharpe vs Base", fontweight="bold", fontsize=11)
ax3.legend(fontsize=8)
ax3.grid(True, alpha=0.25, axis="x")
for bar, val in zip(bars2, sharpes):
    ax3.text(val + 0.01, bar.get_y() + bar.get_height()/2,
             f"{val:.2f}", va="center", fontsize=7.5)

ax4 = fig.add_subplot(gs[2, 0])
cost_mults   = [r[0] for r in cost_results]
cost_cagrs   = [r[2]["cagr"] * 100 for r in cost_results]
cost_sharpes = [r[2]["sharpe"] for r in cost_results]

ax4.plot(cost_mults, cost_cagrs, "o-", color="#2563EB",
         lw=1.8, markersize=6, label="CAGR")
ax4_r = ax4.twinx()
ax4_r.plot(cost_mults, cost_sharpes, "s--", color="#7C3AED",
           lw=1.4, markersize=5, label="Sharpe")
ax4.axhline(0, color="#EF4444", lw=1.0, ls=":", alpha=0.7)
ax4.axvline(1.0, color="gray", lw=0.8, ls="--", alpha=0.5)
ax4.set_xlabel("Cost multiplier  (1× = 0.268%/side)")
ax4.set_ylabel("CAGR (%)", color="#2563EB")
ax4_r.set_ylabel("Sharpe", color="#7C3AED")
ax4.set_title("CAGR & Sharpe vs Transaction Cost", fontweight="bold", fontsize=11)
lines1, labels1 = ax4.get_legend_handles_labels()
lines2, labels2 = ax4_r.get_legend_handles_labels()
ax4.legend(lines1 + lines2, labels1 + labels2, fontsize=8)
ax4.grid(True, alpha=0.25)
for x, y in zip(cost_mults, cost_cagrs):
    ax4.annotate(f"{y:.1f}%", (x, y), textcoords="offset points",
                 xytext=(0, 8), ha="center", fontsize=7.5, color="#2563EB")

ax5 = fig.add_subplot(gs[2, 1])
mdds      = [abs(stress_results[n]["mdd"]) * 100 for n in names_bar]
base_mdd  = abs(base_m.get("mdd", 0)) * 100
col_mdd   = ["#059669" if m < base_mdd else "#EF4444" for m in mdds]

bars3 = ax5.barh(range(len(names_bar)), mdds,
                 color=col_mdd, alpha=0.75, height=0.6)
ax5.axvline(base_mdd, color="#2563EB", lw=1.8, ls="--",
            label=f"Base {base_mdd:.1f}%")
ax5.set_yticks(range(len(names_bar)))
ax5.set_yticklabels([n.split(":")[1].strip() for n in names_bar], fontsize=8)
ax5.set_xlabel("Max Drawdown (%)")
ax5.set_title("Stress Max Drawdown (green = better than base)",
              fontweight="bold", fontsize=11)
ax5.legend(fontsize=8)
ax5.grid(True, alpha=0.25, axis="x")
for bar, val in zip(bars3, mdds):
    ax5.text(val + 0.2, bar.get_y() + bar.get_height()/2,
             f"{val:.1f}%", va="center", fontsize=7.5)

fig.suptitle("Kriti 2026 v7.0.1 — Full Stress Test Report",
             fontsize=13, fontweight="bold", y=0.999)
plt.savefig(os.path.join(OUTPUT_DIR, "kriti2026_v7_stress_report.png"), dpi=150, bbox_inches="tight")
plt.close()
print("  Stress chart saved → kriti2026_v7_stress_report.png")

# Save stress results to csv
stress_rows = []
for name, m in stress_results.items():
    stress_rows.append({
        "scenario":    name,
        "cagr_pct":    round(m["cagr"]*100, 2),
        "sharpe":      round(m["sharpe"], 3),
        "sortino":     round(m["sortino"], 3),
        "max_dd_pct":  round(m["mdd"]*100, 2),
        "calmar":      round(m["calmar"], 3),
        "winrate_pct": round(m["winrate"]*100, 1) if not np.isnan(m.get("winrate", float("nan"))) else np.nan,
        "vs_base_pct": round((m["cagr"] - base_cagr)*100, 2),
    })

stress_df = pd.DataFrame(stress_rows)
csv_path  = os.path.join(OUTPUT_DIR, "kriti2026_v7_stress_summary.csv")
stress_df.to_csv(csv_path, index=False)
print(f"  Stress summary CSV saved → {csv_path}")


print(f"\n{'='*60}")
print(f"  Total runtime: {(time.time()-t0)/60:.1f} min")
print(f"  (Stress tests alone: {(time.time()-st0)/60:.1f} min)")
print(f"{'='*60}")